# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'verificarIdade.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_idade = QtWidgets.QLabel(self.centralwidget)
        self.label_idade.setGeometry(QtCore.QRect(160, 180, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_idade.setFont(font)
        self.label_idade.setObjectName("label_idade")
        self.lineEdit_idade = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_idade.setGeometry(QtCore.QRect(300, 180, 181, 22))
        self.lineEdit_idade.setObjectName("lineEdit_idade")
        self.pushButton_verificar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_verificar.setGeometry(QtCore.QRect(340, 240, 101, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_verificar.setFont(font)
        self.pushButton_verificar.setObjectName("pushButton_verificar")
        self.label_resultado = QtWidgets.QLabel(self.centralwidget)
        self.label_resultado.setGeometry(QtCore.QRect(290, 410, 241, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_resultado.setFont(font)
        self.label_resultado.setText("")
        self.label_resultado.setIndent(-2)
        self.label_resultado.setObjectName("label_resultado")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_idade.setText(_translate("MainWindow", "Digite sua idade: "))
        self.pushButton_verificar.setText(_translate("MainWindow", "Verificar"))
