# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'soma.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_titulo = QtWidgets.QLabel(self.centralwidget)
        self.label_titulo.setGeometry(QtCore.QRect(260, 40, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_titulo.setFont(font)
        self.label_titulo.setObjectName("label_titulo")
        self.label_n1 = QtWidgets.QLabel(self.centralwidget)
        self.label_n1.setGeometry(QtCore.QRect(40, 110, 211, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_n1.setFont(font)
        self.label_n1.setObjectName("label_n1")
        self.label_n2 = QtWidgets.QLabel(self.centralwidget)
        self.label_n2.setGeometry(QtCore.QRect(40, 140, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_n2.setFont(font)
        self.label_n2.setObjectName("label_n2")
        self.lineEdit_n1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_n1.setGeometry(QtCore.QRect(250, 110, 431, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_n1.setFont(font)
        self.lineEdit_n1.setObjectName("lineEdit_n1")
        self.lineEdit_n2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_n2.setGeometry(QtCore.QRect(250, 140, 431, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_n2.setFont(font)
        self.lineEdit_n2.setObjectName("lineEdit_n2")
        self.pushButton_somar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_somar.setGeometry(QtCore.QRect(330, 240, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_somar.setFont(font)
        self.pushButton_somar.setObjectName("pushButton_somar")
        self.label_resultado = QtWidgets.QLabel(self.centralwidget)
        self.label_resultado.setGeometry(QtCore.QRect(220, 410, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_resultado.setFont(font)
        self.label_resultado.setObjectName("label_resultado")
        self.label_resultado_resultado = QtWidgets.QLabel(self.centralwidget)
        self.label_resultado_resultado.setGeometry(QtCore.QRect(320, 410, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_resultado_resultado.setFont(font)
        self.label_resultado_resultado.setText("")
        self.label_resultado_resultado.setObjectName("label_resultado_resultado")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_titulo.setText(_translate("MainWindow", "Soma de Dois Números"))
        self.label_n1.setText(_translate("MainWindow", "Digite o primeiro número:"))
        self.label_n2.setText(_translate("MainWindow", "Digite o segundo número:"))
        self.pushButton_somar.setText(_translate("MainWindow", "Somar"))
        self.label_resultado.setText(_translate("MainWindow", "Resultado: "))
