from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_titulo = QtWidgets.QLabel(self.centralwidget)
        self.label_titulo.setGeometry(QtCore.QRect(310, 30, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_titulo.setFont(font)
        self.label_titulo.setObjectName("label_titulo")
        self.label_entrada = QtWidgets.QLabel(self.centralwidget)
        self.label_entrada.setGeometry(QtCore.QRect(170, 190, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_entrada.setFont(font)
        self.label_entrada.setObjectName("label_entrada")
        self.lineEdit_numero = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_numero.setGeometry(QtCore.QRect(310, 190, 181, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_numero.setFont(font)
        self.lineEdit_numero.setObjectName("lineEdit_numero")
        self.pushButton_verificar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_verificar.setGeometry(QtCore.QRect(500, 190, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_verificar.setFont(font)
        self.pushButton_verificar.setObjectName("pushButton_verificar")
        self.label_resultado = QtWidgets.QLabel(self.centralwidget)
        self.label_resultado.setGeometry(QtCore.QRect(360, 370, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_resultado.setFont(font)
        self.label_resultado.setText("")
        self.label_resultado.setObjectName("label_resultado")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_titulo.setText(_translate("MainWindow", "Par ou Ímpar?"))
        self.label_entrada.setText(_translate("MainWindow", "Digite um número:"))
        self.pushButton_verificar.setText(_translate("MainWindow", "verificar"))
