# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'blocoNotas.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(0, 0, 801, 541))
        self.textEdit.setObjectName("textEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuArquivo = QtWidgets.QMenu(self.menubar)
        self.menuArquivo.setObjectName("menuArquivo")
        self.menuEditar = QtWidgets.QMenu(self.menubar)
        self.menuEditar.setObjectName("menuEditar")
        self.menuFormatar = QtWidgets.QMenu(self.menubar)
        self.menuFormatar.setObjectName("menuFormatar")
        self.menuExibir = QtWidgets.QMenu(self.menubar)
        self.menuExibir.setObjectName("menuExibir")
        self.menuZoom = QtWidgets.QMenu(self.menuExibir)
        self.menuZoom.setObjectName("menuZoom")
        self.menuAjuda = QtWidgets.QMenu(self.menubar)
        self.menuAjuda.setObjectName("menuAjuda")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNovo = QtWidgets.QAction(MainWindow)
        self.actionNovo.setObjectName("actionNovo")
        self.actionSalvar = QtWidgets.QAction(MainWindow)
        self.actionSalvar.setObjectName("actionSalvar")
        self.actionRestaurar_zoom_padr_o = QtWidgets.QAction(MainWindow)
        self.actionRestaurar_zoom_padr_o.setObjectName("actionRestaurar_zoom_padr_o")
        self.actionAmpliar = QtWidgets.QAction(MainWindow)
        self.actionAmpliar.setObjectName("actionAmpliar")
        self.actionReduzir = QtWidgets.QAction(MainWindow)
        self.actionReduzir.setObjectName("actionReduzir")
        self.actionSair = QtWidgets.QAction(MainWindow)
        self.actionSair.setObjectName("actionSair")
        self.actionAbrir = QtWidgets.QAction(MainWindow)
        self.actionAbrir.setObjectName("actionAbrir")
        self.menuArquivo.addAction(self.actionNovo)
        self.menuArquivo.addAction(self.actionSalvar)
        self.menuArquivo.addAction(self.actionSair)
        self.menuArquivo.addAction(self.actionAbrir)
        self.menuZoom.addAction(self.actionRestaurar_zoom_padr_o)
        self.menuZoom.addAction(self.actionAmpliar)
        self.menuZoom.addAction(self.actionReduzir)
        self.menuExibir.addAction(self.menuZoom.menuAction())
        self.menubar.addAction(self.menuArquivo.menuAction())
        self.menubar.addAction(self.menuEditar.menuAction())
        self.menubar.addAction(self.menuFormatar.menuAction())
        self.menubar.addAction(self.menuExibir.menuAction())
        self.menubar.addAction(self.menuAjuda.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuArquivo.setTitle(_translate("MainWindow", "Arquivo"))
        self.menuEditar.setTitle(_translate("MainWindow", "Editar"))
        self.menuFormatar.setTitle(_translate("MainWindow", "Formatar"))
        self.menuExibir.setTitle(_translate("MainWindow", "Exibir"))
        self.menuZoom.setTitle(_translate("MainWindow", "Zoom"))
        self.menuAjuda.setTitle(_translate("MainWindow", "Ajuda"))
        self.actionNovo.setText(_translate("MainWindow", "Novo"))
        self.actionNovo.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionSalvar.setText(_translate("MainWindow", "Salvar"))
        self.actionSalvar.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionRestaurar_zoom_padr_o.setText(_translate("MainWindow", "Restaurar zoom padrão"))
        self.actionAmpliar.setText(_translate("MainWindow", "Ampliar"))
        self.actionReduzir.setText(_translate("MainWindow", "Reduzir"))
        self.actionSair.setText(_translate("MainWindow", "Sair"))
        self.actionSair.setShortcut(_translate("MainWindow", "Esc"))
        self.actionAbrir.setText(_translate("MainWindow", "Abrir"))
        self.actionAbrir.setShortcut(_translate("MainWindow", "Ctrl+O"))
