# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'exibirNome.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(799, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_titulo = QtWidgets.QLabel(self.centralwidget)
        self.label_titulo.setGeometry(QtCore.QRect(150, 40, 501, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_titulo.setFont(font)
        self.label_titulo.setObjectName("label_titulo")
        self.label_nome = QtWidgets.QLabel(self.centralwidget)
        self.label_nome.setGeometry(QtCore.QRect(50, 140, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_nome.setFont(font)
        self.label_nome.setObjectName("label_nome")
        self.pushButton_exibir = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_exibir.setGeometry(QtCore.QRect(310, 230, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_exibir.setFont(font)
        self.pushButton_exibir.setObjectName("pushButton_exibir")
        self.labelExibir_nome = QtWidgets.QLabel(self.centralwidget)
        self.labelExibir_nome.setGeometry(QtCore.QRect(300, 380, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelExibir_nome.setFont(font)
        self.labelExibir_nome.setText("")
        self.labelExibir_nome.setObjectName("labelExibir_nome")
        self.lineEdit_nome = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_nome.setGeometry(QtCore.QRect(160, 140, 501, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_nome.setFont(font)
        self.lineEdit_nome.setObjectName("lineEdit_nome")
        self.label_idade = QtWidgets.QLabel(self.centralwidget)
        self.label_idade.setGeometry(QtCore.QRect(50, 180, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_idade.setFont(font)
        self.label_idade.setObjectName("label_idade")
        self.lineEdit_idade = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_idade.setGeometry(QtCore.QRect(160, 180, 501, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_idade.setFont(font)
        self.lineEdit_idade.setObjectName("lineEdit_idade")
        self.labelExibir_idade = QtWidgets.QLabel(self.centralwidget)
        self.labelExibir_idade.setGeometry(QtCore.QRect(290, 440, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelExibir_idade.setFont(font)
        self.labelExibir_idade.setText("")
        self.labelExibir_idade.setObjectName("labelExibir_idade")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 799, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_titulo.setText(_translate("MainWindow", "Programa Para Exibir Nome Digitado"))
        self.label_nome.setText(_translate("MainWindow", "Digite Nome:"))
        self.pushButton_exibir.setText(_translate("MainWindow", "Exibir Informações"))
        self.label_idade.setText(_translate("MainWindow", "Digite Nome:"))
