# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pokemon.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(904, 692)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_titulo = QtWidgets.QLabel(self.centralwidget)
        self.label_titulo.setGeometry(QtCore.QRect(240, 10, 431, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_titulo.setFont(font)
        self.label_titulo.setStyleSheet("color: rgb(255, 98, 8);")
        self.label_titulo.setObjectName("label_titulo")
        self.radioButton_op1 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_op1.setGeometry(QtCore.QRect(600, 230, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radioButton_op1.setFont(font)
        self.radioButton_op1.setStyleSheet("color: rgb(255, 0, 0);")
        self.radioButton_op1.setObjectName("radioButton_op1")
        self.radioButton_op2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_op2.setGeometry(QtCore.QRect(600, 270, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radioButton_op2.setFont(font)
        self.radioButton_op2.setStyleSheet("color: rgb(255, 0, 0);")
        self.radioButton_op2.setObjectName("radioButton_op2")
        self.radioButton_op3 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_op3.setGeometry(QtCore.QRect(600, 310, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radioButton_op3.setFont(font)
        self.radioButton_op3.setStyleSheet("color: rgb(255, 0, 0);")
        self.radioButton_op3.setObjectName("radioButton_op3")
        self.radioButton_op4 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_op4.setGeometry(QtCore.QRect(600, 350, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radioButton_op4.setFont(font)
        self.radioButton_op4.setStyleSheet("color: rgb(255, 0, 0);")
        self.radioButton_op4.setObjectName("radioButton_op4")
        self.label_img = QtWidgets.QLabel(self.centralwidget)
        self.label_img.setGeometry(QtCore.QRect(150, 180, 321, 321))
        self.label_img.setText("")
        self.label_img.setPixmap(QtGui.QPixmap("img/sombraPikachu.png"))
        self.label_img.setScaledContents(True)
        self.label_img.setObjectName("label_img")
        self.pushButton_adivinhar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_adivinhar.setGeometry(QtCore.QRect(610, 420, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_adivinhar.setFont(font)
        self.pushButton_adivinhar.setStyleSheet("background-color: rgb(82, 30, 255);\n"
"border: 2px solid rgb(33, 35, 153);\n"
"color: rgb(255, 255, 0);")
        self.pushButton_adivinhar.setObjectName("pushButton_adivinhar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 904, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_titulo.setText(_translate("MainWindow", "Quem é esse Pokémon?"))
        self.radioButton_op1.setText(_translate("MainWindow", "Charmander"))
        self.radioButton_op2.setText(_translate("MainWindow", "Pikachu"))
        self.radioButton_op3.setText(_translate("MainWindow", "Raichu"))
        self.radioButton_op4.setText(_translate("MainWindow", "Bulbasaur"))
        self.pushButton_adivinhar.setText(_translate("MainWindow", "?"))
