# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jogoSonic.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(924, 683)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(240, 0, 441, 61))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("color: #fa8a0a;\n"
"font-size: 40px;\n"
"\n"
"")
        self.label_title.setTextFormat(QtCore.Qt.AutoText)
        self.label_title.setWordWrap(False)
        self.label_title.setObjectName("label_title")
        self.pushButton_selectSonic = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_selectSonic.setGeometry(QtCore.QRect(160, 80, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.pushButton_selectSonic.setFont(font)
        self.pushButton_selectSonic.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_selectSonic.setStyleSheet("QPushButton{\n"
"background-color: #2533b8;\n"
"border: 2px solid #192275;\n"
"color: white;\n"
"border-radius: 5px;\n"
"}\n"
"")
        self.pushButton_selectSonic.setObjectName("pushButton_selectSonic")
        self.pushButton_selectTails = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_selectTails.setGeometry(QtCore.QRect(280, 80, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.pushButton_selectTails.setFont(font)
        self.pushButton_selectTails.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_selectTails.setStyleSheet("QPushButton{\n"
"background-color: #dec62c;\n"
"border: 2px solid #c27a29;\n"
"color: white;\n"
"border-radius: 5px;\n"
"}\n"
"")
        self.pushButton_selectTails.setObjectName("pushButton_selectTails")
        self.pushButton_selectAmy = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_selectAmy.setGeometry(QtCore.QRect(400, 80, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.pushButton_selectAmy.setFont(font)
        self.pushButton_selectAmy.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_selectAmy.setStyleSheet("QPushButton{\n"
"background-color: #f035dd;\n"
"border: 2px solid #9c218f;\n"
"color: white;\n"
"border-radius: 5px;\n"
"}\n"
"")
        self.pushButton_selectAmy.setObjectName("pushButton_selectAmy")
        self.pushButton_selectKnuckles = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_selectKnuckles.setGeometry(QtCore.QRect(520, 80, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.pushButton_selectKnuckles.setFont(font)
        self.pushButton_selectKnuckles.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_selectKnuckles.setStyleSheet("QPushButton{\n"
"background-color: #d92e2e;\n"
"border: 2px solid #941e1e;\n"
"color: white;\n"
"border-radius: 5px;\n"
"}\n"
"")
        self.pushButton_selectKnuckles.setObjectName("pushButton_selectKnuckles")
        self.pushButton_selectShadow = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_selectShadow.setGeometry(QtCore.QRect(640, 80, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.pushButton_selectShadow.setFont(font)
        self.pushButton_selectShadow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_selectShadow.setStyleSheet("QPushButton{\n"
"background-color: #242323;\n"
"border: 2px solid #121212;\n"
"color: white;\n"
"border-radius: 5px;\n"
"}\n"
"")
        self.pushButton_selectShadow.setObjectName("pushButton_selectShadow")
        self.pushButton_play = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_play.setGeometry(QtCore.QRect(390, 560, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        self.pushButton_play.setFont(font)
        self.pushButton_play.setStyleSheet("QPushButton{\n"
"background-color: #28b526;\n"
"border: 2px solid #1a7519;\n"
"color: white;\n"
"border-radius: 10px;\n"
"}\n"
"")
        self.pushButton_play.setObjectName("pushButton_play")
        self.label_fundo = QtWidgets.QLabel(self.centralwidget)
        self.label_fundo.setGeometry(QtCore.QRect(0, 0, 931, 691))
        self.label_fundo.setText("")
        self.label_fundo.setPixmap(QtGui.QPixmap("img/fundo.jpg"))
        self.label_fundo.setScaledContents(True)
        self.label_fundo.setObjectName("label_fundo")
        self.label_personagemSelecionado = QtWidgets.QLabel(self.centralwidget)
        self.label_personagemSelecionado.setGeometry(QtCore.QRect(330, 220, 261, 271))
        self.label_personagemSelecionado.setText("")
        self.label_personagemSelecionado.setScaledContents(False)
        self.label_personagemSelecionado.setObjectName("label_personagemSelecionado")
        self.label_fundo.raise_()
        self.label_title.raise_()
        self.pushButton_selectSonic.raise_()
        self.pushButton_selectTails.raise_()
        self.pushButton_selectAmy.raise_()
        self.pushButton_selectKnuckles.raise_()
        self.pushButton_selectShadow.raise_()
        self.pushButton_play.raise_()
        self.label_personagemSelecionado.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 924, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_title.setText(_translate("MainWindow", "Escolha seu Personagem"))
        self.pushButton_selectSonic.setText(_translate("MainWindow", "Sonic"))
        self.pushButton_selectTails.setText(_translate("MainWindow", "Tails"))
        self.pushButton_selectAmy.setText(_translate("MainWindow", "Amy"))
        self.pushButton_selectKnuckles.setText(_translate("MainWindow", "Knuckles"))
        self.pushButton_selectShadow.setText(_translate("MainWindow", "Shadow"))
        self.pushButton_play.setText(_translate("MainWindow", "Play"))
