# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculadora.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_titulo = QtWidgets.QLabel(self.centralwidget)
        self.label_titulo.setGeometry(QtCore.QRect(340, 30, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_titulo.setFont(font)
        self.label_titulo.setObjectName("label_titulo")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(290, 140, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(290, 180, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_num1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_num1.setGeometry(QtCore.QRect(370, 140, 113, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_num1.setFont(font)
        self.lineEdit_num1.setObjectName("lineEdit_num1")
        self.lineEdit_num2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_num2.setGeometry(QtCore.QRect(370, 180, 113, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_num2.setFont(font)
        self.lineEdit_num2.setObjectName("lineEdit_num2")
        self.pushButton_calcular = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_calcular.setGeometry(QtCore.QRect(360, 280, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_calcular.setFont(font)
        self.pushButton_calcular.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_calcular.setObjectName("pushButton_calcular")
        self.label_resultado = QtWidgets.QLabel(self.centralwidget)
        self.label_resultado.setGeometry(QtCore.QRect(60, 360, 711, 141))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_resultado.setFont(font)
        self.label_resultado.setText("")
        self.label_resultado.setWordWrap(True)
        self.label_resultado.setObjectName("label_resultado")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_titulo.setText(_translate("MainWindow", "Calculadora"))
        self.label_2.setText(_translate("MainWindow", "Número 1:"))
        self.label_3.setText(_translate("MainWindow", "Número 2:"))
        self.pushButton_calcular.setText(_translate("MainWindow", "Calcular"))
