# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'exer4.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(290, 50, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(300, 140, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_num = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_num.setGeometry(QtCore.QRect(400, 140, 113, 20))
        self.lineEdit_num.setObjectName("lineEdit_num")
        self.pushButton_contar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_contar.setGeometry(QtCore.QRect(370, 200, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_contar.setFont(font)
        self.pushButton_contar.setObjectName("pushButton_contar")
        self.label_contagem = QtWidgets.QLabel(self.centralwidget)
        self.label_contagem.setGeometry(QtCore.QRect(370, 270, 241, 261))
        self.label_contagem.setText("")
        self.label_contagem.setObjectName("label_contagem")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Contagem Regressiva"))
        self.label_2.setText(_translate("MainWindow", "Número Inteiro:"))
        self.pushButton_contar.setText(_translate("MainWindow", "Contar"))
